- name: Jinja template test
  hosts: localhost

  vars:
    my_list: [1, 2, 3, 4]
    my_dict: {"name": "Peter", "age": 28, "nationality": "Hungarian", "male": true}

  tasks:
    - name: Using Jinja template in list
      set_fact:
        message: |
          {% for item in my_list %}
          {% if item % 2 == 0 %}
          - {{ item }} is even
          {% else %}
          - {{ item }} is odd
          {% endif %}
          {% endfor %}

    - name: Print
      debug:
        var: message

    - name: Using Jinja template in dict
      set_fact:
        message2: |
          {% for key, value in my_dict.items() %}
          Key: {{ key }}, Value: {{ value }}
          {% endfor %}

    - name: Print
      debug:
        var: message2
          