---
- name: Install and start nginx service
  hosts: all
  tasks:
    - name: Install nginx service
      become: true
      apt:
        name: nginx
        state: latest

    - name: Start nginx service
      become: true
      service:
        name: nginx
        state: started
